container:
  length: 20.0
  width: 10.0
  height: 10.0
  max_weight: 1000.0
algorithm:
  type: all
  params:
    genetic:
      population_size: 30
      generations: 50
visualization:
  show_3d: true
  show_2d: true
  show_weight_distribution: true
cargo_data:
  path: ''
  random_generation:
    count: 15
    min_size: 1.0
    max_size: 5.0
    min_weight: 1.0
    max_weight: 100.0
